### ISSUE TITLE
cannot install via brew

### ISSUE THREAD

**Issue by heroturtle** [typesense/homebrew-tap#2]
## Description

Installing via brew doesn't work

## Steps to reproduce

brew update && brew upgrade
brew install typesense/tap/typesense-server@0.23.1

## Expected Behavior

installs Typesense

## Actual Behavior

Does not install. Error:
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences.

## Metadata

**Typesense Version**: 0.23.1

**OS**: 12.6.1-x86_64

**Xcode**: 14.1

**Comment by jasonbosco** [comment]
This seems like a homebrew installation issue. You want to follow the instructions in the error message and update your command line tools.
